---
title: FailFastException
ms.custom: 
ms.date: 03/30/2017
ms.prod: .net-framework
ms.reviewer: 
ms.suite: 
ms.technology: dotnet-clr
ms.tgt_pltfrm: 
ms.topic: article
ms.assetid: f30de0d9-3a91-4800-9d09-3504d7e5a10f
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
manager: wpickett
ms.openlocfilehash: 27def01a4747521bef29b47a2a458e2ed24190b3
ms.sourcegitcommit: ce279f2d7fe2220e6ea0a25a8a7a5370ddf8d9f0
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 12/02/2017
---
# <a name="failfastexception"></a>FailFastException
ID : 103  
  
 Gravité : Erreur  
  
 Catégorie : suivi  
  
## <a name="description"></a>Description  
 Une exception a été levée pendant FailFast. L'événement répertorie l'exception, le nom de processus et l'ID de processus.  
  
## <a name="see-also"></a>Voir aussi  
 [Journalisation des événements](../../../../../docs/framework/wcf/diagnostics/event-logging/index.md)  
 [Référence générale des événements](../../../../../docs/framework/wcf/diagnostics/event-logging/events-general-reference.md)
