---
title: FailFastException
ms.custom: 
ms.date: 03/30/2017
ms.prod: .net-framework
ms.reviewer: 
ms.suite: 
ms.technology: dotnet-clr
ms.tgt_pltfrm: 
ms.topic: article
ms.assetid: f30de0d9-3a91-4800-9d09-3504d7e5a10f
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
manager: wpickett
ms.workload: dotnet
ms.openlocfilehash: deff4cd29e2a7a0ab2f50dcaf30c787a5856a8dc
ms.sourcegitcommit: 16186c34a957fdd52e5db7294f291f7530ac9d24
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 12/22/2017
---
# <a name="failfastexception"></a>FailFastException
ID : 103  
  
 Gravité : Erreur  
  
 Catégorie : suivi  
  
## <a name="description"></a>Description  
 Une exception a été levée pendant FailFast. L'événement répertorie l'exception, le nom de processus et l'ID de processus.  
  
## <a name="see-also"></a>Voir aussi  
 [Journalisation des événements](../../../../../docs/framework/wcf/diagnostics/event-logging/index.md)  
 [Informations de référence générales sur les événements](../../../../../docs/framework/wcf/diagnostics/event-logging/events-general-reference.md)
