---
title: '&#39;Lever&#39; instruction ne peut pas omettre l’opérande en dehors un &#39;Catch&#39; instruction ou à l’intérieur un &#39;enfin&#39; instruction'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: e426e0d7af685fae82d8dc64a95803bdacb543e0
ms.sourcegitcommit: 64f4baed249341e5bf64d1385bf48e3f2e1a0211
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 09/07/2018
ms.locfileid: "44098353"
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a><span data-ttu-id="1ef48-102">&#39;Lever&#39; instruction ne peut pas omettre l’opérande en dehors un &#39;Catch&#39; instruction ou à l’intérieur un &#39;enfin&#39; instruction</span><span class="sxs-lookup"><span data-stu-id="1ef48-102">&#39;Throw&#39; statement cannot omit operand outside a &#39;Catch&#39; statement or inside a &#39;Finally&#39; statement</span></span>
<span data-ttu-id="1ef48-103">Les instructions`Throw` situées en dehors de l’instruction `Catch` doivent fournir le nom d’un objet exception.</span><span class="sxs-lookup"><span data-stu-id="1ef48-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="1ef48-104">**ID d’erreur :** BC30666</span><span class="sxs-lookup"><span data-stu-id="1ef48-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="1ef48-105">Pour corriger cette erreur</span><span class="sxs-lookup"><span data-stu-id="1ef48-105">To correct this error</span></span>  
  
1.  <span data-ttu-id="1ef48-106">Spécifiez le nom d’un objet d’exception dérivé de `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="1ef48-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2.  <span data-ttu-id="1ef48-107">Restructurez votre code pour que l’instruction `Throw` se trouve dans un bloc `Catch` .</span><span class="sxs-lookup"><span data-stu-id="1ef48-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="1ef48-108">Voir aussi</span><span class="sxs-lookup"><span data-stu-id="1ef48-108">See Also</span></span>  
 [<span data-ttu-id="1ef48-109">Throw (instruction)</span><span class="sxs-lookup"><span data-stu-id="1ef48-109">Throw Statement</span></span>](../../visual-basic/language-reference/statements/throw-statement.md)  
 [<span data-ttu-id="1ef48-110">Try...Catch...Finally (instruction)</span><span class="sxs-lookup"><span data-stu-id="1ef48-110">Try...Catch...Finally Statement</span></span>](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [<span data-ttu-id="1ef48-111">Classe d’exception dans Visual Basic</span><span class="sxs-lookup"><span data-stu-id="1ef48-111">Exception Class in Visual Basic</span></span>](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [<span data-ttu-id="1ef48-112">Exceptions et gestion des erreurs dans Visual Basic</span><span class="sxs-lookup"><span data-stu-id="1ef48-112">Exception and Error Handling in Visual Basic</span></span>](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
