---
title: "Guide pratique pour gérer une exception à l’aide de try/catch (Guide de programmation C#)"
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
dev_langs:
- CSharp
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
caps.latest.revision: 14
author: BillWagner
ms.author: wiwagn
translation.priority.ht:
- cs-cz
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- pl-pl
- pt-br
- ru-ru
- tr-tr
- zh-cn
- zh-tw
ms.translationtype: HT
ms.sourcegitcommit: 306c608dc7f97594ef6f72ae0f5aaba596c936e1
ms.openlocfilehash: f6f714cd1b652845e77405ff74fbfc860e71dc21
ms.contentlocale: fr-fr
ms.lasthandoff: 07/28/2017

---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="a647e-102">Guide pratique pour gérer une exception à l'aide de try/catch (Guide de programmation C#)</span><span class="sxs-lookup"><span data-stu-id="a647e-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="a647e-103">L’objectif d’un bloc [try-catch](../../../csharp/language-reference/keywords/try-catch.md) est d’intercepter et de gérer une exception générée par du code opérationnel.</span><span class="sxs-lookup"><span data-stu-id="a647e-103">The purpose of a [try-catch](../../../csharp/language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="a647e-104">Certaines exceptions peuvent être gérées dans un bloc `catch` et le problème résolu sans que l’exception soit levée à nouveau, mais le plus souvent la seule chose que vous puissiez faire est de vous assurer que l’exception appropriée est levée.</span><span class="sxs-lookup"><span data-stu-id="a647e-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="a647e-105">Exemple</span><span class="sxs-lookup"><span data-stu-id="a647e-105">Example</span></span>  
 <span data-ttu-id="a647e-106">Dans cet exemple, <xref:System.IndexOutOfRangeException> n’est pas l’exception la plus appropriée : <xref:System.ArgumentOutOfRangeException> a de plus de sens pour la méthode car l’erreur est provoquée par l’argument `index` passé par l’appelant.</span><span class="sxs-lookup"><span data-stu-id="a647e-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 <span data-ttu-id="a647e-107">[!code-cs[csProgGuideExceptions#5](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/how-to-handle-an-exception-using-try-catch_1.cs)]</span><span class="sxs-lookup"><span data-stu-id="a647e-107">[!code-cs[csProgGuideExceptions#5](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/how-to-handle-an-exception-using-try-catch_1.cs)]</span></span>  
  
## <a name="comments"></a><span data-ttu-id="a647e-108">Commentaires</span><span class="sxs-lookup"><span data-stu-id="a647e-108">Comments</span></span>  
 <span data-ttu-id="a647e-109">Le code qui provoque une exception est cloisonné dans le bloc `try`.</span><span class="sxs-lookup"><span data-stu-id="a647e-109">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="a647e-110">Une instruction `catch` est ajoutée juste après pour gérer `IndexOutOfRangeException`, si elle se produit.</span><span class="sxs-lookup"><span data-stu-id="a647e-110">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="a647e-111">Le bloc `catch` gère `IndexOutOfRangeException` et lève l’exception plus appropriée `ArgumentOutOfRangeException` à la place.</span><span class="sxs-lookup"><span data-stu-id="a647e-111">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="a647e-112">Pour fournir à l’appelant autant d’informations que possible, pensez à spécifier l’exception d’origine comme <xref:System.Exception.InnerException%2A> de la nouvelle exception.</span><span class="sxs-lookup"><span data-stu-id="a647e-112">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="a647e-113">Comme la propriété <xref:System.Exception.InnerException%2A> a la valeur [readonly](../../../csharp/language-reference/keywords/readonly.md), vous devez l’affecter dans le constructeur de la nouvelle exception.</span><span class="sxs-lookup"><span data-stu-id="a647e-113">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../../csharp/language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="a647e-114">Voir aussi</span><span class="sxs-lookup"><span data-stu-id="a647e-114">See Also</span></span>  
 <span data-ttu-id="a647e-115">[Guide de programmation C#](../../../csharp/programming-guide/index.md) </span><span class="sxs-lookup"><span data-stu-id="a647e-115">[C# Programming Guide](../../../csharp/programming-guide/index.md) </span></span>  
 <span data-ttu-id="a647e-116">[Exceptions et gestion des exceptions](../../../csharp/programming-guide/exceptions/index.md) </span><span class="sxs-lookup"><span data-stu-id="a647e-116">[Exceptions and Exception Handling](../../../csharp/programming-guide/exceptions/index.md) </span></span>  
 [<span data-ttu-id="a647e-117">Gestion des exceptions</span><span class="sxs-lookup"><span data-stu-id="a647e-117">Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/exception-handling.md)

